name: master_project
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^5.5.0+1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.1+1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/svg/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
